import {
  Text,
  Hash,
  Clock,
  Image,
  FolderOpen,
  Fingerprint,
  Key,
  MapPin,
  Wifi,
  Binary,
  FileText,
  Globe,
  File,
  Database,
  Shield,
  Send,
  Activity,
  Type,
  Palette,
  Keyboard,
  Camera,
  QrCode,
  ScrollText,
  Volume2,
  Coins,
  AudioLines,
  Timer,
  Contact,
  Calculator,
  Wallet2,
  Code,
  Regex,
  Eye,
  GitCompare,
  PiggyBank,
  Clipboard,
} from "lucide-react";

import type { ITool } from "@/types";

export const tools: ITool[] = [
  {
    id: "uuid",
    title: "UUID Generator",
    shortTitle: "UUID",
    description:
      "Generate universally unique identifiers with multiple versions and batch options",
    icon: Hash,
    color: "bg-blue-500",
    category: "Text & Data Generators",
    tags: ["uuid", "guid", "identifier", "unique"],
    features: [
      "Version 4 (Random)",
      "Version 1 (Timestamp)",
      "Batch Generation",
      "Copy to Clipboard",
    ],
    popular: true,
    href: "/uuid",
    seo: {
      title: "UUID Generator - Generate Unique Identifiers",
      description:
        "Create UUIDs with various versions and batch options. Perfect for developers needing unique identifiers.",
      keywords: "uuid, guid, identifier, unique, generator",
    },
  },
  {
    id: "lorem-ipsum",
    title: "Lorem Ipsum Generator",
    shortTitle: "Lorem Ipsum",
    description:
      "Generate placeholder text in various formats including words, sentences, and paragraphs with customization options",
    icon: FileText,
    color: "bg-amber-500",
    category: "Text & Data Generators",
    tags: ["lorem", "ipsum", "placeholder", "text", "generator", "dummy"],
    features: [
      "Words, Sentences & Paragraphs",
      "Multiple Languages",
      "Custom Length",
      "HTML Formatting",
      "Copy to Clipboard",
    ],
    popular: true,
    href: "/lorem-ipsum",
    seo: {
      title: "Lorem Ipsum Generator - Generate Placeholder Text",
      description:
        "Generate Lorem Ipsum placeholder text with custom length options. Perfect for designers and developers needing dummy content.",
      keywords: "lorem ipsum, placeholder text, dummy text, generator, content",
    },
  },
  {
    id: "timestamp",
    title: "Timestamp Converter",
    shortTitle: "Timestamp",
    description:
      "Convert, generate, and solve timestamps in various formats with batch processing",
    icon: Clock,
    color: "bg-green-500",
    category: "Format Converters",
    tags: ["timestamp", "unix", "date", "time", "convert"],
    features: [
      "Live Current Time",
      "Custom Date/Time",
      "Batch Convert",
      "Multiple Formats",
    ],
    popular: true,
    href: "/timestamp",
    seo: {
      title: "Timestamp Converter - Convert and Generate Timestamps",
      description:
        "Convert timestamps to various formats, generate current time, and batch process dates. Ideal for developers and data analysts.",
      keywords: "timestamp, unix, date, time, convert, generator",
    },
  },
  {
    id: "jwt",
    title: "JWT Decoder/Encoder",
    shortTitle: "JWT",
    description:
      "Decode, encode, and verify JSON Web Tokens with support for multiple algorithms",
    icon: Fingerprint,
    color: "bg-red-500",
    category: "Security Tools",
    tags: ["jwt", "token", "authentication", "security"],
    features: [
      "Decode JWTs",
      "Encode JWTs",
      "Verify Signatures",
      "Support for Multiple Algorithms",
    ],
    popular: true,
    href: "/jwt",
    seo: {
      title: "JWT Decoder/Encoder - Manage JSON Web Tokens",
      description:
        "Decode, encode, and verify JWTs with support for various algorithms. Essential for secure web applications.",
      keywords: "jwt, token, authentication, security, decoder, encoder",
    },
  },
  {
    id: "image-format-converter",
    title: "Image Format Converter",
    shortTitle: "Image Converter",
    description:
      "Convert images between formats like PNG, JPEG, GIF, and WebP with batch processing",
    icon: Image,
    color: "bg-orange-500",
    category: "Format Converters",
    tags: ["image", "converter", "png", "jpeg", "gif", "webp"],
    features: [
      "Batch Conversion",
      "Multiple Formats",
      "Resize and Optimize",
      "Download Converted Images",
    ],
    popular: true,
    href: "/image-converter",
    seo: {
      title: "Image Format Converter - Convert Images Easily",
      description:
        "Convert images between various formats like PNG, JPEG, GIF, and WebP. Supports batch processing and optimization.",
      keywords: "image, converter, png, jpeg, gif, webp, batch",
    },
  },
  {
    id: "text-case-converter",
    title: "Text Case Converter",
    shortTitle: "Text Converter",
    description:
      "Convert text between different cases like uppercase, lowercase, title case, and more",
    icon: Text,
    color: "bg-teal-500",
    category: "Format Converters",
    tags: ["text", "converter", "case", "uppercase", "lowercase", "title case"],
    features: ["Uppercase", "Lowercase", "Title Case", "Sentence Case"],
    popular: false,
    href: "/text-converter",
    seo: {
      title: "Text Case Converter - Convert Text Cases Easily",
      description:
        "Convert text between different cases like uppercase, lowercase, title case, and more. Perfect for writers and developers.",
      keywords: "text, converter, case, uppercase, lowercase, title case",
    },
  },
  {
    id: "base64",
    title: "Base64 Encoder/Decoder",
    shortTitle: "Base64",
    description:
      "Encode and decode text, files, and URLs to/from Base64 format with support for different encodings",
    icon: Binary,
    color: "bg-purple-500",
    category: "Format Converters",
    tags: ["base64", "encode", "decode", "converter", "encoding", "binary"],
    features: [
      "Text to Base64",
      "Base64 to Text",
      "File Encoding",
      "URL Safe Base64",
      "Multiple Character Sets",
    ],
    popular: true,
    href: "/base64",
    seo: {
      title: "Base64 Encoder/Decoder - Convert Text and Files",
      description:
        "Encode and decode text, files, and URLs to/from Base64 format. Supports URL-safe encoding and multiple character sets.",
      keywords:
        "base64, encode, decode, converter, encoding, binary, text, file",
    },
  },
  {
    id: "nextjs-image-decoder",
    title: "Next.js Image URL Decoder",
    shortTitle: "Next.js Image",
    description:
      "Decode and encode Next.js optimized image URLs with bulk processing, multi-size generation, and parameter extraction",
    icon: Image,
    color: "bg-emerald-500",
    category: "Format Converters",
    tags: [
      "nextjs",
      "next.js",
      "image",
      "url",
      "decoder",
      "encoder",
      "optimization",
      "converter",
      "decode",
      "encode",
      "parameters",
      "bulk",
    ],
    features: [
      "Decode Next.js Image URLs",
      "Generate Optimized URLs",
      "Bulk URL Processing",
      "Multi-Size Generation",
      "Extract Original Sources",
      "Custom Width & Quality",
      "JSON Export",
      "Copy to Clipboard",
    ],
    popular: false,
    href: "/nextjs-image-decoder",
    seo: {
      title:
        "Next.js Image URL Decoder - Extract & Generate Optimized Image URLs",
      description:
        "Decode Next.js image optimization URLs to extract original sources, generate optimized URLs with custom parameters, and bulk process multiple image links.",
      keywords:
        "nextjs image decoder, next.js image url, image optimization, url decoder, image url encoder, decode image url, extract image url, responsive images",
    },
  },
  {
    id: "folder-analyzer",
    title: "Folder Structure Analyzer",
    shortTitle: "Folder Analyzer",
    description:
      "Analyze, visualize, and export folder structures with advanced filtering, statistics, and multi-format export options",
    icon: FolderOpen,
    color: "bg-blue-500",
    category: "File & Document Tools",
    tags: [
      "folder",
      "directory",
      "structure",
      "tree",
      "export",
      "analyze",
      "files",
    ],
    features: [
      "Interactive Tree View",
      "Smart File Filtering",
      "Multi-Format Export",
      "Detailed Statistics",
    ],
    popular: false,
    href: "/folder-analyzer",
    seo: {
      title: "Folder Structure Analyzer - Visualize and Export Directory Trees",
      description:
        "Analyze folder structures, visualize directory trees, filter files by type and size, and export in JSON, CSV, XML formats. Perfect for developers and system administrators.",
      keywords:
        "folder structure, directory tree, file analyzer, export folder, file organization, directory mapping",
    },
  },
  {
    id: "password-generator",
    title: "Password Generator",
    shortTitle: "Password",
    description:
      "Generate secure passwords, passphrases, and PINs with advanced customization and security analysis",
    icon: Key,
    color: "bg-red-500",
    category: "Security Tools",
    tags: [
      "password",
      "generator",
      "security",
      "passphrase",
      "pin",
      "encryption",
    ],
    features: [
      "Advanced Password Generation",
      "Passphrase Generator",
      "PIN & Code Generator",
      "Batch Generation",
      "Security Analysis",
    ],
    popular: true,
    href: "/password-generator",
    seo: {
      title: "Password Generator - Create Secure Passwords",
      description:
        "Generate strong passwords, memorable passphrases, and secure PINs with real-time security analysis. Features batch generation, custom presets, and entropy calculation.",
      keywords:
        "password generator, secure password, passphrase, PIN generator, security, encryption, strong password",
    },
  },
  {
    id: "ip-location",
    title: "IP Location Checker",
    shortTitle: "IP Location",
    description:
      "Check IP address geolocation information including country, region, city, ISP, and more",
    icon: MapPin,
    color: "bg-indigo-500",
    category: "Network & Monitoring",
    tags: [
      "ip",
      "location",
      "geolocation",
      "network",
      "country",
      "region",
      "city",
      "isp",
    ],
    features: [
      "IP Geolocation Lookup",
      "ISP Information",
      "Country & Region Details",
      "Timezone Detection",
      "Batch IP Processing",
    ],
    popular: false,
    href: "/ip-location",
    seo: {
      title: "IP Location Checker - Find IP Address Geolocation",
      description:
        "Check IP address location, ISP information, country, region, city, and timezone. Support for both IPv4 and IPv6 addresses with batch processing.",
      keywords:
        "ip location, geolocation, ip address, country, region, city, isp, timezone, network tools",
    },
  },
  {
    id: "speed-test",
    title: "Internet Speed Test",
    shortTitle: "Speed Test",
    description:
      "Test your internet connection speed with download, upload, and ping measurements",
    icon: Wifi,
    color: "bg-green-500",
    category: "Network & Monitoring",
    tags: [
      "speed",
      "test",
      "internet",
      "download",
      "upload",
      "ping",
      "bandwidth",
      "connection",
    ],
    features: [
      "Download Speed Test",
      "Upload Speed Test",
      "Ping Latency Test",
      "Real-time Progress",
      "Speed History",
    ],
    popular: true,
    href: "/speed-test",
    seo: {
      title: "Internet Speed Test - Test Your Connection Speed",
      description:
        "Test your internet connection speed with accurate download, upload, and ping measurements. Real-time testing with detailed results and history.",
      keywords:
        "internet speed test, bandwidth test, download speed, upload speed, ping test, connection test, network speed",
    },
  },
  {
    id: "dns-lookup",
    title: "DNS Lookup Tool",
    shortTitle: "DNS Lookup",
    description:
      "Query DNS records including A, AAAA, MX, CNAME, TXT, NS, and more with detailed results",
    icon: Globe,
    color: "bg-cyan-500",
    category: "Network & Monitoring",
    tags: [
      "dns",
      "lookup",
      "domain",
      "records",
      "nameserver",
      "mx",
      "cname",
      "txt",
      "network",
    ],
    features: [
      "Multiple Record Types",
      "A, AAAA, MX, CNAME, TXT, NS",
      "Batch Domain Lookup",
      "Response Time Display",
      "Export Results",
    ],
    popular: true,
    href: "/dns-lookup",
    seo: {
      title: "DNS Lookup Tool - Query Domain Name System Records",
      description:
        "Perform DNS lookups for domains with support for A, AAAA, MX, CNAME, TXT, NS, and other record types. Get detailed DNS information with response times.",
      keywords:
        "dns lookup, domain records, nameserver, mx records, cname, txt records, dns query, network tools",
    },
  },
  {
    id: "cron-scheduler",
    title: "API Cron Job Scheduler",
    shortTitle: "API Cron Scheduler",
    description:
      "Schedule and manage API calls with cron expressions. Run automated tasks with a visual dashboard and detailed logging",
    icon: Clock,
    color: "bg-purple-500",
    category: "Development & API",
    tags: [
      "cron",
      "scheduler",
      "api",
      "automation",
      "jobs",
      "tasks",
      "webhook",
      "monitoring",
    ],
    features: [
      "Cron Expression Builder",
      "API Call Scheduling",
      "Real-time Dashboard",
      "Execution Logs",
      "Job Management",
    ],
    popular: true,
    href: "/cron-scheduler",
    seo: {
      title: "Cron Job Scheduler - Schedule Automated API Calls",
      description:
        "Schedule API calls and webhooks using cron expressions. Features real-time dashboard, execution logs, and job management. Perfect for automation and monitoring.",
      keywords:
        "cron scheduler, api automation, webhook scheduler, job scheduler, cron jobs, task automation, api monitoring",
    },
  },
  {
    id: "pdf-toolkit",
    title: "PDF Toolkit",
    shortTitle: "PDF Tools",
    description:
      "Comprehensive PDF manipulation tools - split, merge, rotate, add watermarks, insert text, and extract information",
    icon: File,
    color: "bg-red-600",
    category: "File & Document Tools",
    tags: [
      "pdf",
      "split",
      "merge",
      "rotate",
      "watermark",
      "text",
      "toolkit",
      "documents",
      "manipulation",
      "extract",
    ],
    features: [
      "Split PDFs by Pages/Chunks",
      "Merge Multiple PDFs",
      "Rotate Pages",
      "Add Watermarks",
      "Insert Text",
      "Extract Information",
      "Create New PDFs",
      "Browser-based Processing",
    ],
    popular: true,
    href: "/pdf-toolkit",
    seo: {
      title: "PDF Toolkit - Comprehensive PDF Manipulation Tools",
      description:
        "Split, merge, rotate PDFs, add watermarks, insert text, and more. All processing happens in your browser for privacy and security. Perfect for document management.",
      keywords:
        "pdf tools, pdf split, pdf merge, pdf rotate, pdf watermark, pdf text, document manipulation, pdf toolkit, file processing",
    },
  },
  {
    id: "mock-data-generator",
    title: "Mock Data Generator",
    shortTitle: "Mock Data",
    description:
      "Generate realistic fake user data, addresses, and emails using Faker.js for testing and development",
    icon: Database,
    color: "bg-emerald-500",
    category: "Text & Data Generators",
    tags: [
      "mock",
      "fake",
      "data",
      "generator",
      "users",
      "addresses",
      "emails",
      "faker",
      "testing",
      "development",
    ],
    features: [
      "Generate User Profiles",
      "Generate Addresses",
      "Generate Email Data",
      "Multiple Locales",
      "JSON Export",
      "Batch Generation",
      "Customizable Options",
    ],
    popular: true,
    href: "/mock-data-generator",
    seo: {
      title: "Mock Data Generator - Generate Fake Data for Testing",
      description:
        "Generate realistic fake user data, addresses, and emails using Faker.js. Perfect for testing, development, and prototyping with multiple locales and export options.",
      keywords:
        "mock data, fake data, generator, users, addresses, emails, faker, testing, development, prototyping, json",
    },
  },
  {
    id: "hmac-generator",
    title: "HMAC Generator & Verifier",
    shortTitle: "HMAC",
    description:
      "Generate and verify Hash-based Message Authentication Codes using various algorithms for secure authentication and data integrity verification",
    icon: Shield,
    color: "bg-slate-500",
    category: "Security Tools",
    tags: [
      "hmac",
      "hash",
      "authentication",
      "security",
      "integrity",
      "cryptography",
      "verification",
      "sha256",
      "sha512",
    ],
    features: [
      "Generate HMAC Signatures",
      "Verify HMAC Authenticity",
      "Multiple Hash Algorithms",
      "SHA-1, SHA-256, SHA-384, SHA-512",
      "Secure Key Input",
      "Copy to Clipboard",
    ],
    popular: true,
    href: "/hmac-generator",
    seo: {
      title:
        "HMAC Generator & Verifier - Generate and Verify Message Authentication Codes",
      description:
        "Generate and verify secure HMAC codes using SHA-256, SHA-512, and other algorithms. Perfect for API authentication, data integrity verification, and secure token validation.",
      keywords:
        "hmac generator, hmac verifier, hash authentication, message authentication code, sha256, sha512, api security, data integrity, cryptography, verification",
    },
  },
  {
    id: "api-tester",
    title: "API Testing Tool",
    shortTitle: "API Tester",
    description:
      "Professional API testing tool with request builder, response viewer, history tracking, and collection management - your Postman alternative",
    icon: Send,
    color: "bg-violet-500",
    category: "Development & API",
    tags: [
      "api",
      "rest",
      "http",
      "testing",
      "postman",
      "requests",
      "client",
      "endpoint",
      "development",
      "debugging",
    ],
    features: [
      "HTTP Request Builder",
      "Response Viewer with Formatting",
      "Request History & Collections",
      "Environment Variables",
      "Authentication Support",
      "Response Time & Status Tracking",
      "Export/Import Collections",
      "Batch Testing",
    ],
    popular: true,
    href: "/api-tester",
    seo: {
      title: "API Testing Tool - Professional REST API Client & Tester",
      description:
        "Professional API testing tool with request builder, response viewer, and collection management. Perfect Postman alternative for developers with history tracking and environment variables.",
      keywords:
        "api testing, rest api client, postman alternative, http client, api tool, request builder, api debugging, endpoint testing, development tools",
    },
  },
  {
    id: "uptime-monitor",
    title: "Uptime Monitor",
    shortTitle: "Uptime Monitor",
    description:
      "Monitor website uptime, response times, and availability with real-time status tracking and command-line style visualization",
    icon: Activity,
    color: "bg-blue-600",
    category: "Network & Monitoring",
    tags: [
      "uptime",
      "monitor",
      "website",
      "status",
      "availability",
      "performance",
      "response time",
      "monitoring",
      "health check",
      "downtime",
    ],
    features: [
      "Real-time Website Monitoring",
      "Command-line Style Visualization",
      "Response Time Tracking",
      "Status History Charts",
      "Multiple Site Management",
      "Export Monitoring Data",
      "Uptime Statistics",
      "Customizable Check Intervals",
    ],
    popular: true,
    href: "/uptime-monitor",
    seo: {
      title: "Uptime Monitor - Monitor Website Status & Performance",
      description:
        "Monitor website uptime, response times, and availability with real-time status tracking. Features command-line style visualization, historical data, and comprehensive monitoring tools.",
      keywords:
        "uptime monitor, website monitoring, status tracking, response time, availability, performance monitoring, site health, downtime detection, uptime statistics",
    },
  },
  {
    id: "ascii-generator",
    title: "ASCII Art Generator",
    shortTitle: "ASCII Art",
    description:
      "Convert text and images to ASCII art with customizable fonts, styles, density controls, and export options",
    icon: Type,
    color: "bg-purple-600",
    category: "Design & Creative",
    tags: [
      "ascii",
      "art",
      "text",
      "image",
      "converter",
      "generator",
      "font",
      "style",
      "banner",
      "terminal",
      "monospace",
      "characters",
    ],
    features: [
      "Text to ASCII Art Conversion",
      "Image to ASCII Art Conversion",
      "Multiple ASCII Fonts",
      "Adjustable Character Density",
      "Size and Width Controls",
      "Invert Colors Option",
      "Save and Load ASCII Arts",
      "Export as Text/HTML",
      "Quick Templates",
      "Real-time Preview",
    ],
    popular: true,
    href: "/ascii-generator",
    seo: {
      title: "ASCII Art Generator - Convert Text and Images to ASCII Art",
      description:
        "Create stunning ASCII art from text and images. Features multiple fonts, density controls, export options, and real-time preview. Perfect for terminal art, banners, and creative projects.",
      keywords:
        "ascii art generator, text to ascii, image to ascii, ascii converter, ascii fonts, terminal art, ascii banner, text art, ascii characters, monospace art",
    },
  },
  {
    id: "colors",
    title: "Colors Toolkit",
    shortTitle: "Colors",
    description:
      "Comprehensive color tools with picker, format converter, palette generator, gradients, and accessibility checker",
    icon: Palette,
    color: "bg-pink-500",
    category: "Design & Creative",
    tags: [
      "color",
      "picker",
      "converter",
      "palette",
      "gradient",
      "hex",
      "rgb",
      "hsl",
      "hsv",
      "accessibility",
      "contrast",
      "tailwind",
      "css",
      "design",
      "harmony",
    ],
    features: [
      "Interactive Color Picker",
      "Format Converter (HEX, RGB, HSL, HSV, LAB, CMYK)",
      "Color Harmony Generator",
      "CSS & Tailwind Gradient Generator",
      "Accessibility Contrast Checker",
      "Shades & Tints Generator",
      "Real-time Color Adjustment",
      "Copy in Multiple Formats",
    ],
    popular: true,
    href: "/colors",
    seo: {
      title: "Colors Toolkit - Color Picker, Converter & Palette Generator",
      description:
        "Comprehensive color tools including picker, format converter, palette generator, gradients, and accessibility checker. Perfect for designers and developers.",
      keywords:
        "color picker, color converter, palette generator, hex to rgb, color harmony, accessibility, contrast checker, gradients, tailwind css, design tools",
    },
  },
  {
    id: "keyboard-tester",
    title: "Keyboard Tester",
    shortTitle: "Keyboard",
    description:
      "Test keyboard functionality, monitor key presses, typing speed, and key response times with comprehensive analytics",
    icon: Keyboard,
    color: "bg-indigo-500",
    category: "Hardware Testing",
    tags: [
      "keyboard",
      "testing",
      "keys",
      "typing",
      "speed",
      "monitoring",
      "wpm",
      "response",
      "analytics",
      "events",
      "input",
      "debugging",
    ],
    features: [
      "Real-time Key Monitoring",
      "Typing Speed Testing",
      "Key Event Logging",
      "Response Time Analysis",
      "Sound Feedback",
      "Export Analytics Data",
      "Multiple Test Texts",
      "Comprehensive Statistics",
    ],
    popular: true,
    href: "/keyboard-tester",
    seo: {
      title: "Keyboard Tester - Test Keys, Typing Speed & Response Times",
      description:
        "Comprehensive keyboard testing tool with real-time monitoring, typing speed tests, key response analysis, and detailed analytics. Perfect for testing keyboard functionality and debugging input issues.",
      keywords:
        "keyboard tester, key testing, typing speed test, wpm test, keyboard monitoring, key response time, input debugging, keyboard analytics, key events, typing test",
    },
  },
  {
    id: "camera-mic-tester",
    title: "Camera & Microphone Tester",
    shortTitle: "Camera & Mic",
    description:
      "Test camera and microphone functionality, monitor audio levels, record media, and verify device permissions with comprehensive controls",
    icon: Camera,
    color: "bg-purple-500",
    category: "Hardware Testing",
    tags: [
      "camera",
      "microphone",
      "testing",
      "recording",
      "audio",
      "video",
      "media",
      "devices",
      "permissions",
      "monitoring",
      "levels",
      "quality",
      "debugging",
    ],
    features: [
      "Camera Device Testing",
      "Microphone Audio Monitoring",
      "Real-time Audio Level Display",
      "Video & Audio Recording",
      "Device Permission Status",
      "Quality Settings Control",
      "Media File Download",
      "Multiple Device Support",
    ],
    popular: true,
    href: "/camera-mic-tester",
    seo: {
      title: "Camera & Microphone Tester - Test Media Devices & Record",
      description:
        "Comprehensive camera and microphone testing tool with real-time monitoring, recording capabilities, and device management. Perfect for testing media devices and debugging issues.",
      keywords:
        "camera tester, microphone tester, media device testing, audio recording, video recording, device permissions, audio levels, media debugging, webcam test, mic test",
    },
  },
  {
    id: "qr-generator",
    title: "QR Code Generator",
    shortTitle: "QR Code",
    description:
      "Generate QR codes for text, URLs, contacts, WiFi, and more with customizable styling options",
    icon: QrCode,
    color: "bg-slate-600",
    category: "Text & Data Generators",
    tags: [
      "qr",
      "qrcode",
      "generator",
      "url",
      "wifi",
      "contact",
      "vcard",
      "text",
      "barcode",
      "mobile",
    ],
    features: [
      "Text, URL, Email QR Codes",
      "WiFi & Contact Cards",
      "Customizable Colors & Size",
      "Error Correction Levels",
      "PNG Download",
      "Real-time Generation",
    ],
    popular: true,
    href: "/qr-generator",
    seo: {
      title: "QR Code Generator - Create Custom QR Codes",
      description:
        "Generate QR codes for text, URLs, WiFi, contacts, and more. Customize colors, size, and error correction. Download as PNG with real-time preview.",
      keywords:
        "qr code generator, qr code, barcode, wifi qr, contact qr, url qr, vcard, mobile qr, custom qr code",
    },
  },
  {
    id: "hash-generator",
    title: "Hash Generator",
    shortTitle: "Hash Generator",
    description:
      "Generate MD5, SHA-1, SHA-256, SHA-384, and SHA-512 hashes for text and files with security analysis",
    icon: Shield,
    color: "bg-emerald-600",
    category: "Security Tools",
    tags: [
      "hash",
      "md5",
      "sha1",
      "sha256",
      "sha512",
      "checksum",
      "integrity",
      "security",
      "cryptography",
      "verification",
    ],
    features: [
      "Multiple Hash Algorithms",
      "Text & File Support",
      "Batch Hash Generation",
      "Security Recommendations",
      "Copy & Download Results",
      "Client-side Processing",
    ],
    popular: true,
    href: "/hash-generator",
    seo: {
      title: "Hash Generator - MD5, SHA-256, SHA-512 Hash Calculator",
      description:
        "Generate secure hashes using MD5, SHA-1, SHA-256, SHA-384, and SHA-512 algorithms. Support for text and file input with security recommendations.",
      keywords:
        "hash generator, md5, sha256, sha512, checksum, file hash, text hash, cryptographic hash, integrity verification, security hash",
    },
  },
  {
    id: "privacy-policy-generator",
    title: "Privacy Policy Generator",
    shortTitle: "Privacy Policy",
    description:
      "Generate comprehensive privacy policies for your website or application with GDPR and CCPA compliance options",
    icon: ScrollText,
    color: "bg-violet-600",
    category: "Text & Data Generators",
    tags: [
      "privacy",
      "policy",
      "gdpr",
      "ccpa",
      "legal",
      "compliance",
      "data protection",
      "website",
      "terms",
      "generator",
    ],
    features: [
      "GDPR & CCPA Compliance",
      "Customizable Data Practices",
      "Company Information Forms",
      "Legal Templates",
      "Markdown Export",
      "Privacy Rights Coverage",
    ],
    popular: true,
    href: "/privacy-policy-generator",
    seo: {
      title: "Privacy Policy Generator - Create GDPR & CCPA Compliant Policies",
      description:
        "Generate comprehensive privacy policies with GDPR and CCPA compliance. Customize data practices, user rights, and legal requirements for your website or application.",
      keywords:
        "privacy policy generator, gdpr compliance, ccpa compliance, privacy policy template, data protection, legal generator, website privacy policy, privacy rights",
    },
  },
  {
    id: "speaker-tester",
    title: "Speaker Testing Tool",
    shortTitle: "Speaker Tester",
    description:
      "Test speakers and audio systems with multiple configurations including mono, stereo, surround sound, and custom frequency testing",
    icon: Volume2,
    color: "bg-indigo-600",
    category: "Hardware Testing",
    tags: [
      "speaker",
      "audio",
      "sound",
      "testing",
      "surround",
      "stereo",
      "mono",
      "frequency",
      "5.1",
      "7.1",
      "channels",
      "volume",
      "bass",
      "treble",
    ],
    features: [
      "Multiple Speaker Configurations",
      "Mono, Stereo, 2.1, 4.0, 5.1, 7.1 Testing",
      "Custom Frequency Testing (20Hz-20kHz)",
      "Channel-specific Audio Testing",
      "Automatic Test Sequences",
      "Real-time Volume Control",
      "Test Result Tracking",
      "Audio Device Information",
    ],
    popular: true,
    href: "/speaker-tester",
    seo: {
      title: "Speaker Testing Tool - Test Audio Systems & Surround Sound",
      description:
        "Comprehensive speaker testing tool with support for mono, stereo, 2.1, 4.0, 5.1, 7.1 surround sound configurations. Test frequency response, channel balance, and audio quality.",
      keywords:
        "speaker tester, audio testing, surround sound test, 5.1 test, 7.1 test, frequency test, channel test, speaker configuration, audio system test, sound quality",
    },
  },
  {
    id: "blockchain-balance",
    title: "Blockchain Balances",
    shortTitle: "Blockchain Balances",
    description:
      "Scan wallet balances across multiple blockchain networks including Ethereum, BSC, Polygon, Arbitrum, and more with native and ERC20 token support",
    icon: Coins,
    color: "bg-yellow-500",
    category: "Blockchain & Crypto",
    tags: [
      "blockchain",
      "wallet",
      "balance",
      "ethereum",
      "polygon",
      "bsc",
      "arbitrum",
      "optimism",
      "avalanche",
      "multi-chain",
      "erc20",
      "tokens",
      "portfolio",
      "crypto",
      "defi",
    ],
    features: [
      "Multi-Chain Balance Scanning",
      "Native & ERC20 Token Support",
      "Real-time Balance Updates",
      "Portfolio Overview",
      "8+ Supported Networks",
      "Export Balance Data",
      "Transaction History Links",
      "USD Value Tracking",
    ],
    popular: false,
    href: "/blockchain-balance",
    seo: {
      title: "Blockchain Balance - Multi-Chain Wallet Balance Checker",
      description:
        "Scan wallet balances across Ethereum, BSC, Polygon, Arbitrum, Optimism, and more. Check native and ERC20 token balances with real-time portfolio tracking.",
      keywords:
        "blockchain scanner, wallet balance, multi-chain, ethereum balance, polygon scanner, bsc balance, arbitrum, optimism, crypto portfolio, erc20 tokens, defi tracker",
    },
  },
  {
    id: "eth-converter",
    title: "ETH / Wei / Gwei Converter",
    shortTitle: "ETH Converter",
    description:
      "Convert between Ethereum units (ETH, Wei, Gwei) with real-time parallel updates and copy functionality",
    icon: Coins,
    color: "bg-blue-500",
    category: "Blockchain & Crypto",
    tags: [
      "ethereum",
      "eth",
      "wei",
      "gwei",
      "converter",
      "crypto",
      "blockchain",
      "gas",
      "units",
      "calculator",
    ],
    features: [
      "Real-time Parallel Conversion",
      "ETH ↔ Wei ↔ Gwei",
      "Copy to Clipboard",
      "Conversion Formulas",
      "Gas Price Calculations",
      "Precision Handling",
    ],
    popular: false,
    href: "/eth-converter",
    seo: {
      title: "ETH Wei Gwei Converter - Ethereum Unit Converter",
      description:
        "Convert between Ethereum units (ETH, Wei, Gwei) with real-time updates. Perfect for gas calculations, smart contracts, and DeFi applications.",
      keywords:
        "ethereum converter, eth to wei, wei to gwei, gas price converter, ethereum units, crypto converter, blockchain calculator, smart contract units",
    },
  },
  {
    id: "audio-noise-reduction",
    title: "Audio Noise Reduction",
    shortTitle: "Audio Noise Reduction",
    description:
      "Remove background noise, enhance audio quality with advanced filtering, compression, EQ, and real-time processing",
    icon: AudioLines,
    color: "bg-teal-600",
    category: "Hardware Testing",
    tags: [
      "audio",
      "noise reduction",
      "recording",
      "processing",
      "filters",
      "compression",
      "equalizer",
      "enhancement",
      "professional",
      "real-time",
      "microphone",
      "sound",
      "quality",
      "visualization",
    ],
    features: [
      "Real-time Audio Recording",
      "Noise Reduction",
      "Multi-band EQ & Compression",
      "High/Low Pass Filters",
      "Real-time Visualization",
      "File Upload Support",
      "WAV Export",
      "Browser-based Processing",
    ],
    popular: false,
    href: "/audio-noise-reduction",
    seo: {
      title: "Audio Noise Reduction - Remove Background Noise",
      description:
        "Audio noise reduction tool with advanced filtering, compression, EQ, and real-time processing. Record, enhance, and export high-quality audio directly in your browser.",
      keywords:
        "audio noise reduction, noise removal, audio enhancement, sound processing, audio filters, microphone recording, audio editing, noise gate, audio compression, equalizer, sound quality",
    },
  },
  {
    id: "stopwatch-timer",
    title: "Stopwatch & Timer",
    shortTitle: "Stopwatch & Timer",
    description:
      "Professional stopwatch with lap times, customizable timer with notifications, and comprehensive time management features",
    icon: Timer,
    color: "bg-blue-600",
    category: "Hardware Testing",
    tags: [
      "stopwatch",
      "timer",
      "time",
      "lap",
      "countdown",
      "notification",
      "alert",
      "precision",
      "management",
      "professional",
      "chrono",
      "measurement",
      "tracking",
      "interval",
    ],
    features: [
      "High-Precision Stopwatch",
      "Lap Time Recording",
      "Customizable Timer",
      "Sound Notifications",
      "Settings Persistence",
      "Export Lap Times",
      "Auto-Restart Timer",
      "Real-time Progress",
    ],
    popular: true,
    href: "/stopwatch-timer",
    seo: {
      title: "Stopwatch & Timer - Professional Time Management Tools",
      description:
        "Professional stopwatch with lap time recording and customizable timer with notifications. Features sound alerts, settings persistence, and comprehensive time tracking capabilities.",
      keywords:
        "stopwatch, timer, lap times, countdown timer, time measurement, chrono, notification timer, precision timing, professional stopwatch, time tracking, interval timer, time management",
    },
  },
  {
    id: "vcf",
    title: "VCF (vCard File) Reader & Writer",
    shortTitle: "VCF Tool",
    description:
      "Parse, create, edit, and manage vCard contact files with advanced features including multiple contact support, field validation, and batch operations",
    icon: Contact,
    color: "bg-indigo-500",
    category: "File & Document Tools",
    tags: [
      "vcf",
      "vcard",
      "contacts",
      "address book",
      "phone",
      "email",
      "parsing",
      "generator",
      "export",
      "import",
      "batch",
      "validation",
    ],
    features: [
      "Parse VCF/vCard Files",
      "Generate vCard Contacts",
      "Multiple Contact Support",
      "Field Validation & Error Reporting",
      "Export Individual/Batch Files",
      "Contact Editor Interface",
      "Phone, Email, Address Management",
      "Copy to Clipboard",
    ],
    popular: true,
    href: "/vcf",
    seo: {
      title:
        "VCF vCard File Reader & Writer - Parse and Generate Contact Files",
      description:
        "Parse, create, and manage vCard contact files with comprehensive features. Support for multiple contacts, validation, batch operations, and export functionality.",
      keywords:
        "vcf parser, vcard generator, contact file, address book, phone contacts, email contacts, contact export, contact import, vcard editor, batch contacts",
    },
  },
  {
    id: "ip-calculator",
    title: "IP Address Calculator",
    shortTitle: "IP Calculator",
    description:
      "Comprehensive IP address calculator with subnet calculations, CIDR conversions, binary/hex format conversions, and network analysis",
    icon: Calculator,
    color: "bg-blue-500",
    category: "Network & Monitoring",
    tags: [
      "ip",
      "subnet",
      "cidr",
      "calculator",
      "network",
      "binary",
      "hex",
      "subnetting",
      "mask",
      "wildcard",
      "broadcast",
      "hosts",
      "analysis",
      "ipv4",
      "conversion",
    ],
    features: [
      "Subnet Calculations",
      "CIDR ↔ Subnet Mask Conversion",
      "Binary & Hex Conversions",
      "Custom Subnet Division",
      "Network Class Detection",
      "Private/Public IP Detection",
      "Wildcard Mask Calculation",
      "Host Range Calculation",
      "Export Results",
      "Real-time Validation",
    ],
    popular: true,
    href: "/ip-calculator",
    seo: {
      title: "IP Address Calculator - Subnet Calculator & Network Tools",
      description:
        "Comprehensive IP address calculator with subnet calculations, CIDR conversions, binary/hex format conversions, custom subnetting, and network analysis. Perfect for network engineers and IT professionals.",
      keywords:
        "ip calculator, subnet calculator, cidr calculator, ip subnet, network calculator, binary conversion, hex conversion, wildcard mask, broadcast address, network analysis, subnetting tool, ipv4 calculator",
    },
  },
  {
    id: "evm-vanity",
    title: "EVM Vanity Address Generator",
    shortTitle: "EVM Vanity",
    description:
      "Generate custom Ethereum vanity addresses with specific patterns, prefix/suffix matching, and comprehensive statistics",
    icon: Wallet2,
    color: "bg-purple-500",
    category: "Blockchain & Crypto",
    tags: [
      "ethereum",
      "vanity",
      "address",
      "generator",
      "evm",
      "blockchain",
      "crypto",
      "wallet",
      "private key",
      "custom",
      "pattern",
      "prefix",
      "suffix",
      "hex",
      "client-side",
    ],
    features: [
      "Pattern-based Address Generation",
      "Prefix, Suffix & Contains Matching",
      "Real-time Generation Statistics",
      "Difficulty Level Controls",
      "Private Key Management",
      "Export Results (JSON)",
      "Client-side Processing",
      "Security Best Practices",
      "Estimated Time Calculations",
      "Batch Result Management",
    ],
    popular: true,
    href: "/evm-vanity",
    seo: {
      title:
        "EVM Vanity Address Generator - Generate Custom Ethereum Addresses",
      description:
        "Generate custom Ethereum vanity addresses with specific patterns. Features prefix/suffix matching, real-time statistics, difficulty controls, and secure client-side processing. Perfect for creating memorable wallet addresses.",
      keywords:
        "evm vanity address generator, ethereum vanity address, custom wallet address, blockchain address generator, vanity ethereum address, crypto address generator, ethereum wallet generator, custom evm address, vanity address tool, blockchain vanity generator",
    },
  },
  {
    id: "json-formatter",
    title: "JSON/XML/YAML Formatter & Validator",
    shortTitle: "Data Formatter",
    description:
      "Format, validate, and convert between JSON, XML, YAML, and TOML formats with syntax highlighting and error detection",
    icon: Code,
    color: "bg-orange-500",
    category: "Format Converters",
    tags: [
      "json",
      "xml",
      "yaml",
      "toml",
      "formatter",
      "validator",
      "converter",
      "parser",
      "syntax",
      "beautify",
      "minify",
      "lint",
    ],
    features: [
      "Format & Beautify JSON/XML/YAML/TOML",
      "Syntax Validation & Error Detection",
      "Convert Between Formats",
      "Minify & Compress Data",
      "Real-time Syntax Highlighting",
      "Error Line Highlighting",
      "Copy & Download Results",
      "Multiple Format Support",
    ],
    popular: true,
    href: "/json-formatter",
    seo: {
      title: "JSON XML YAML Formatter - Format, Validate & Convert Data",
      description:
        "Format, validate, and convert between JSON, XML, YAML, and TOML formats. Features syntax highlighting, error detection, minification, and format conversion.",
      keywords:
        "json formatter, xml formatter, yaml formatter, toml formatter, json validator, data formatter, json beautifier, xml validator, yaml validator, format converter, json minifier, data converter",
    },
  },
  {
    id: "regex-tester",
    title: "Regular Expression Tester & Builder",
    shortTitle: "Regex Tester",
    description:
      "Test, build, and debug regular expressions with real-time matching, explanations, and common pattern library",
    icon: Regex,
    color: "bg-green-500",
    category: "Development & API",
    tags: [
      "regex",
      "regexp",
      "pattern",
      "matching",
      "testing",
      "validation",
      "search",
      "replace",
      "javascript",
      "programming",
    ],
    features: [
      "Real-time Pattern Testing",
      "Match Highlighting",
      "Pattern Explanation",
      "Common Regex Library",
      "Replace Functionality",
      "Flags Support (g, i, m, s)",
      "Test String Generator",
      "Export Results",
    ],
    popular: true,
    href: "/regex-tester",
    seo: {
      title: "Regex Tester - Test and Debug Regular Expressions",
      description:
        "Test regular expressions with real-time matching, pattern explanations, and common regex library. Perfect for developers debugging patterns and learning regex.",
      keywords:
        "regex tester, regular expression, pattern matching, regex debugger, regex validator, javascript regex, regex tutorial, pattern testing, regex builder, regex generator",
    },
  },
  {
    id: "markdown-editor",
    title: "Markdown Editor & Preview",
    shortTitle: "Markdown Editor",
    description:
      "Write and preview Markdown with live rendering, syntax highlighting, table editor, and export options",
    icon: Eye,
    color: "bg-blue-500",
    category: "Format Converters",
    tags: [
      "markdown",
      "md",
      "editor",
      "preview",
      "github",
      "documentation",
      "writing",
      "formatting",
      "html",
      "export",
    ],
    features: [
      "Live Preview",
      "Syntax Highlighting",
      "GitHub Flavored Markdown",
      "Table Editor",
      "Export to HTML/PDF",
      "Custom CSS Themes",
      "Math Support (LaTeX)",
      "Mermaid Diagrams",
    ],
    popular: true,
    href: "/markdown-editor",
    seo: {
      title: "Markdown Editor - Write and Preview Markdown",
      description:
        "Online markdown editor with live preview, GitHub flavored markdown, table editor, and export options. Perfect for documentation, README files, and technical writing.",
      keywords:
        "markdown editor, md editor, markdown preview, github markdown, documentation editor, readme editor, markdown to html, technical writing, markdown table, live preview",
    },
  },
  {
    id: "sql-formatter",
    title: "SQL Query Formatter & Validator",
    shortTitle: "SQL Formatter",
    description:
      "Format, validate, and optimize SQL queries with support for multiple database dialects and syntax highlighting",
    icon: Database,
    color: "bg-indigo-500",
    category: "Development & API",
    tags: [
      "sql",
      "query",
      "formatter",
      "validator",
      "database",
      "mysql",
      "postgresql",
      "sqlite",
      "oracle",
      "syntax",
      "optimize",
    ],
    features: [
      "Format & Beautify SQL",
      "Syntax Validation",
      "Multiple Database Dialects",
      "Query Optimization Tips",
      "Minify SQL Queries",
      "Real-time Error Detection",
      "Copy & Download Results",
      "Common Query Templates",
    ],
    popular: true,
    href: "/sql-formatter",
    seo: {
      title: "SQL Formatter - Format and Validate SQL Queries",
      description:
        "Format, validate, and optimize SQL queries with support for MySQL, PostgreSQL, SQLite, and Oracle. Features syntax highlighting, error detection, and query optimization tips.",
      keywords:
        "sql formatter, sql validator, query formatter, sql beautifier, database query, mysql formatter, postgresql formatter, sql syntax, query optimizer, sql minifier",
    },
  },
  {
    id: "diff-checker",
    title: "Diff Checker & Text Comparison",
    shortTitle: "Diff Checker",
    description:
      "Advanced text and file comparison tool with side-by-side diff visualization, merge conflict resolution, and multiple export formats",
    icon: GitCompare,
    color: "bg-purple-500",
    category: "Development & API",
    tags: [
      "diff",
      "comparison",
      "text",
      "file",
      "merge",
      "git",
      "patch",
      "version control",
      "code",
      "changes",
      "unified",
      "split",
    ],
    features: [
      "Side-by-Side & Unified Views",
      "Advanced Diff Algorithms",
      "Ignore Whitespace & Case Options",
      "Line-by-Line Comparison",
      "Character-Level Inline Changes",
      "Export to Patch/HTML/JSON",
      "File Upload Support",
      "Merge Conflict Resolution",
      "Context Line Controls",
      "Statistics & Analytics",
    ],
    popular: true,
    href: "/diff-checker",
    seo: {
      title: "Diff Checker - Advanced Text and File Comparison Tool",
      description:
        "Compare texts and files with advanced diff algorithms, side-by-side visualization, and export options. Perfect for developers, writers, and version control workflows.",
      keywords:
        "diff checker, text comparison, file comparison, diff tool, merge conflicts, patch generator, version control, code comparison, text diff, file diff, git diff, unified diff",
    },
  },
  {
    id: "free-images",
    title: "Free Images Collection",
    shortTitle: "Free Images",
    description:
      "Browse, download, and use high-quality free images with advanced search, filtering, and preview features",
    icon: Image,
    color: "bg-green-600",
    category: "Design & Creative",
    tags: [
      "images",
      "free",
      "photos",
      "gallery",
      "download",
      "preview",
      "search",
      "filter",
      "creative",
      "resources",
      "stock",
      "photography",
    ],
    features: [
      "High-Quality Image Collection",
      "Advanced Search & Filtering",
      "Grid & List View Modes",
      "Image Preview & Details",
      "One-Click URL Copying",
      "Direct Download",
      "Favorites Management",
      "Share Functionality",
    ],
    popular: true,
    href: "/free-images",
    seo: {
      title: "Free Images Collection - High-Quality Stock Photos",
      description:
        "Browse and download high-quality free images with advanced search, filtering, and preview features. Perfect for designers, developers, and content creators.",
      keywords:
        "free images, stock photos, high quality images, image gallery, free photography, creative resources, image download, stock images, free photos, image collection",
    },
  },
  {
    id: "financial-calculator",
    title: "Financial Calculator",
    shortTitle: "Financial Calc",
    description:
      "Calculate interest, APR, loans, mortgages, investments, and other financial calculations with compound interest support",
    icon: PiggyBank,
    color: "bg-emerald-500",
    category: "Text & Data Generators",
    tags: [
      "finance",
      "calculator",
      "interest",
      "apr",
      "loan",
      "mortgage",
      "investment",
      "compound",
      "savings",
      "commercial",
      "business",
      "money",
    ],
    features: [
      "Compound Interest Calculator",
      "Loan & Mortgage Calculator",
      "Investment Growth Projections",
      "APR & APY Conversions",
      "Payment Schedule Generator",
      "Multiple Calculation Types",
      "Export Results",
      "Real-time Calculations",
    ],
    popular: true,
    href: "/financial-calculator",
    seo: {
      title: "Financial Calculator - Interest, Loan, Investment Calculator",
      description:
        "Calculate compound interest, loan payments, mortgage calculations, investment growth, APR/APY conversions. Professional financial calculator for business and personal use.",
      keywords:
        "financial calculator, compound interest calculator, loan calculator, mortgage calculator, investment calculator, apr calculator, apy calculator, interest calculator, savings calculator, business calculator",
    },
  },
  {
    id: "tailwind-colors",
    title: "Tailwind Color Picker",
    shortTitle: "Tailwind Colors",
    description:
      "Browse and copy all Tailwind CSS colors with multiple format options including HEX, RGB, HSL, CSS classes, and OKLCH",
    icon: Palette,
    color: "bg-cyan-500",
    category: "Design & Creative",
    tags: [
      "tailwind",
      "colors",
      "css",
      "palette",
      "picker",
      "hex",
      "rgb",
      "hsl",
      "oklch",
      "classes",
      "design",
      "development",
    ],
    features: [
      "Complete Tailwind CSS Color Palette",
      "Multiple Format Support",
      "One-Click Copy to Clipboard",
      "Search & Filter Colors",
      "Visual Feedback",
      "Responsive Design",
    ],
    popular: true,
    href: "/tailwind-colors",
    seo: {
      title: "Tailwind Color Picker - Browse and Copy Tailwind CSS Colors",
      description:
        "Browse the complete Tailwind CSS color palette and copy colors in HEX, RGB, HSL, CSS classes, and OKLCH formats. Perfect for developers using Tailwind CSS.",
      keywords:
        "tailwind colors, tailwind css, color picker, css colors, hex colors, rgb colors, hsl colors, oklch colors, tailwind classes, design tools, web development",
    },
  },
  {
    id: "clipboard-image-saver",
    title: "Clipboard Image Saver",
    shortTitle: "Clipboard Image",
    description:
      "Paste images from clipboard, convert formats, resize, and save with clipboard history management",
    icon: Clipboard,
    color: "bg-rose-500",
    category: "Design & Creative",
    tags: [
      "clipboard",
      "image",
      "paste",
      "screenshot",
      "save",
      "convert",
      "download",
      "format",
      "resize",
      "history",
    ],
    features: [
      "Paste Images from Clipboard (Ctrl+V)",
      "Clipboard History Management",
      "Format Conversion (PNG, JPEG, WebP, BMP)",
      "Quality & Resize Controls",
      "Batch Download Support",
      "Copy Back to Clipboard",
      "Session-based Privacy",
      "Real-time Preview",
    ],
    popular: true,
    href: "/clipboard-image-saver",
    seo: {
      title: "Clipboard Image Saver - Paste & Save Clipboard Images",
      description:
        "Paste images from clipboard, convert formats, resize, and save. Perfect for screenshots, web images, and quick image saving with clipboard history management.",
      keywords:
        "clipboard image saver, paste image, screenshot tool, clipboard manager, save clipboard image, image format converter, clipboard history, image paste tool, screenshot saver, web image saver",
    },
  },
];
